name: auth_app_flutter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  provider: ^6.1.1
  auto_route: ^5.0.0
  get_it: ^7.2.0
  shared_preferences: ^2.0.15
  sqflite: ^2.3.0
  path_provider: ^2.1.1


dev_dependencies:
  auto_route_generator: ^5.0.0
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  json_serializable: ^6.3.1
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
